Make package global
kuzzleio/kuzzle-cli pull request #3
Opened 2019-11-04 11:58 UTC by Aschen

## What does this PR do ?

Make the package global to be able to do:
```
kuzzle <command>
```

2019-11-09 20:29 UTC, alexandrebouthinon requested changes
I think this is not a good idea to remove Node.js 6 compatibility for now. It's still used by Kuzzle v1 to make it start. Maybe we should create a new major version to perform those enhancements? :slightly_smiling_face:

2019-11-11 09:35 UTC, Aschen commented
> I think this is not a good idea to remove Node.js 6 compatibility for now. It's still used by Kuzzle v1 to make it start. Maybe we should create a new major version to perform those enhancements? slightly_smiling_face

The standalone CLI is only used by Kuzzle v2. Kuzzle v1 still have the [Embedded CLI](https://github.com/kuzzleio/kuzzle/tree/master/bin) in the `bin` directory

2019-11-12 09:09 UTC, scottinet approved these changes

2019-11-12 16:41 UTC, alexandrebouthinon approved these changes

2019-11-13 10:59 UTC, merged